name : Python playwright tests
on : 
  push :
    branches : [main]
  
  pull_request :
    branches : [main]

jobs :
  build :  
    runs-on : ubuntu-latest

    steps :
    - name : This is a buid job
      run : echo "This is a build job"

  tests :
    needs : build  
    runs-on : ubuntu-latest

    steps :
    - name : This is a test job
      run : echo "This is a test job"

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install playwright
      run: pip install playwright
      
    - name: Run tests
      run: pytest --html=reports/index.html
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path : reports

    -name: Display to Github Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports

  deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: This is a deploy job
      run: echo "This is a deploy job"


    